### ISSUE TITLE
Use release and getOrCreateChan multiple times

### ISSUE THREAD

**Issue by wy-os** [FunctionStream/function-stream#159]
In NewSourceTube and NewSinkTube, both getOrCreateChan and release are called, which can result in each topic being "GET" twice and "release" twice，such as :
![image](https://github.com/FunctionStream/function-stream/assets/105999518/ce95dc0a-d8ca-4af4-9921-d54c7720c6f1)

**Comment by RobertIndie** [comment]
The log looks normal. The internal chan will only be closed when the current_use_count reaches to 0 during the release.
