### ISSUE TITLE
I meet the problem when I try to add actions for project.

### ISSUE THREAD

**Issue by janyawat** [FunctionStream/function-stream#51]
I meet the problem when I try to add actions for project.

The actions can run in single layer project but can't in composited project cause of it can't install the dependence corrently.

### **github actions with one layer can run corrently:**
![image](https://user-images.githubusercontent.com/13276719/123345444-a676bc80-d588-11eb-96a3-013c6304b1b5.png)
![image](https://user-images.githubusercontent.com/13276719/123345454-ae366100-d588-11eb-98b8-1e48390ad3da.png)

### but will raise some problem in two layer construction:
![image](https://user-images.githubusercontent.com/13276719/123345562-ed64b200-d588-11eb-8fa3-43aad0770352.png)
![image](https://user-images.githubusercontent.com/13276719/123345716-43395a00-d589-11eb-8940-f93a233767ac.png)

I also think it's not a good idea that put two project together, and it may bring other problems when config other plugins or dependences.

_Originally posted by @winnd in https://github.com/FunctionStream/function-stream/discussions/50_

**Comment by winnd** [comment]
I solved this problem by add `working-directory: front-end` in steps = =

**It worked**
![image](https://user-images.githubusercontent.com/13276719/123505375-520b3400-d691-11eb-8487-68cdafe1e5b6.png)


Maybe the structure of project can be preserved...?

**Comment by RobertIndie** [comment]
@janyawat Thanks for your issue. I think we can solve these problems if we set up a correct working directory. Are there any other problems that I haven't considered?
